config/routes.rb
Rails.application.routes.draw do

  get 'pages/info'
  get 'pages/top'

  resources :spots
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('pages/top')

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :spots
end

app/models/spot.rb
class Spot < ApplicationRecord
  default_scope -> { order(tanada_level_id: :asc, prefecture_id: :asc) }

  has_many :comments
  belongs_to :tanada_level
  belongs_to :prefecture

  mount_uploader :picture, PictureUploader

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, 
  presence: { message: "何か入力して下さい。" },
  length: { in: 2..30, message: "2〜30文字で入力して下さい。" }

  validates :postcode,    length: { maximum: 7 }
  validates :address,     length: { maximum: 30 }
  validates :mapcode,     length: { maximum: 15 }
  #validates :latitude,    numericality: true
  #validates :longitude,   numericality: true
  validates :access,      length: { maximum: 100 }

  validates :url,         length: { maximum: 100 }
  validates :memo,        length: { maximum: 500 }

  # file size check
  validate :file_size, if: "picture.nil?"

  def file_size
    if picture.file.size.to_f/(1000*1000) > 2
      errors.add(:picture, "2MB以内でお願いします!")
    elsif picture.file.size.to_f/(1000*1000) < 0.01
      errors.add(:picture, "ファイルが小さ過ぎます。10KB以上でお願いします。")
    end
  end

end

app/models/tanada_level.rb
class TanadaLevel < ApplicationRecord
  has_many :spots
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def info
  end

  def top
  end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]

  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
    @tanada_level = TanadaLevel.find_by_id(@spot.tanada_level_id)
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(spot_params)

    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render :show, status: :created, location: @spot }
      else
        format.html { render :new }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1
  # PATCH/PUT /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render :edit }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_url, notice: 'Spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spot_params
      params.require(:spot).permit(:name, :prefecture_id, :postcode, :address, :mapcode, :lat, :lng, :access, :tanada_level_id, :url, :picture, :memo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"

  def markdown(text)
    render_options = {
      escape_html:true,
      hard_wrap: true
    }
    extensions = {
      #highlight: true
    }
    renderer = Redcarpet::Render::HTML.new(render_options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    markdown.render(text).html_safe
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tnd</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/info.html.erb
<h1>info</h1>
<p>infoです</p>

app/views/pages/top.html.erb
<h1>Welcome</h1>
<p></p>

app/views/shared/_footer.html.erb
<footer>
  <p>Copyright &copy; 2016 ay. All Rights Reserved.</p>
</footer>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">棚田へGo</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/spots">棚田一覧</a></li>
        <li><a href="/pages/info">Info</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/spots/_form.html.erb
<%= form_for(spot) do |f| %>
  <% if spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% spot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :prefecture_id, '都道府県' %>
    <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :postcode %>
    <%= f.number_field :postcode %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :mapcode %>
    <%= f.number_field :mapcode %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :access %>
    <%= f.text_area :access %>
  </div>

 <div class="field">
   <%= f.label :tanada_level_id, '分類' %>
   <%= f.collection_select :tanada_level_id, TanadaLevel.all, :id, :name %>
 </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_area :url %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
  </div>

  <div class="field">
    <%= f.label :memo %>
    <%= f.text_area :memo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spots/edit.html.erb
<h1>Editing Spot</h1>

<%= render 'form', spot: @spot %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>

app/views/spots/index.html.erb
<p id="notice"><%= notice %></p>

<% @spots.in_groups_of(5) do |group| %>
  <div class="row">
    <% group.compact.each do |spot| %>
      <div class="col-md-3">
        <%= if spot.picture? then image_tag spot.picture_url(:thumb) else image_tag 'thumb_ine.JPG', :size => '200x150' end %>
        <h4><%= link_to spot.name, spot %></h4>
        @<%= spot.prefecture_id %> <%= spot.tanada_level_id %>
      </div>
    <% end %>
  </div>
<% end %>
<br />

<%= link_to 'New Spot', new_spot_path %>

app/views/spots/new.html.erb
<h1>New Spot</h1>

<%= render 'form', spot: @spot %>

<%= link_to 'Back', spots_path %>

app/views/spots/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-9">
    <%= image_tag(@spot.picture_url, width: 400) if @spot.picture.present? %>
  </div>

  <div class="col-md-9">
    <h3><%= @spot.name %></h3>
  </div>

  <div class="col-md-9">
    <ul>
    <li><b>住所:    </b><%= @spot.address %></li>
    <li><b>Mapcode: </b><%= @spot.mapcode %></li>
    <li><b>Access:  </b><%= markdown @spot.access %></li><br>
    <li><b>Memo:    </b><%= markdown @spot.memo %></li>
    <li><b>カテゴリー: </b><%= @tanada_level.name %></li>
    <li><b>参考サイト: </b><%= link_to @spot.url %></li>
    <li><b>緯度経度:   </b><%= @spot.latitude %>, <%= @spot.longitude %></li>
    </ul>
  </div>

  <div class="col-md-9">
    <p>
      <%= link_to 'Edit', edit_spot_path(@spot) %> |
      <%= link_to 'Destroy', @spot, data: { confirm: '削除してもいいですか?' }, method: :delete %> |
      <%= link_to 'Back', spots_path %>
    </p>
  </div>
  </div>

</div>